### ISSUE TITLE
Could't pick Video 

### ISSUE THREAD

**Issue by hey7fine** [jisungbin/ArtDirector#1]
I could't pick any videos ,when i using this:
`ArtDirector(mediaType = MediaType.Video) { }`

that runs:
`java.lang.NoSuchMethodError: No virtual method loadThumbnail(Landroid/net/Uri;Landroid/util/Size;Landroid/os/CancellationSignal;)Landroid/graphics/Bitmap; in class Landroid/content/ContentResolver; or its super classes (declaration of 'android.content.ContentResolver' appears in /system/framework/framework.jar)
        at io.github.jisungbin.artdirector.Media.getVideoThumbnail(Media.kt:49)
        at io.github.jisungbin.artdirector.ArtDirectorKt$ArtDirector$2$invoke$$inlined$items$1.invoke(LazyGrid.kt:295)
        at io.github.jisungbin.artdirector.ArtDirectorKt$ArtDirector$2$invoke$$inlined$items$1.invoke(LazyGrid.kt:135)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:135)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.foundation.lazy.LazyGridScopeImpl$items$1$1.invoke(LazyGrid.kt:235)
        at androidx.compose.foundation.lazy.LazyGridScopeImpl$items$1$1.invoke(LazyGrid.kt:235)
...
`

on Device Android 11

**Comment by hey7fine** [comment]
oh  I have forget my device just on Android 9，this issue happened on Device Android 9 and lower

**Comment by jisungbin** [comment]
`ContentResolver.loadThumbnail` api is added in Android 10. [[#]](https://developer.android.com/reference/android/content/ContentResolver#loadThumbnail(android.net.Uri,%20android.util.Size,%20android.os.CancellationSignal)) I am currently developing this library, and I will fix this bug later. thank you!
